# Generated by Django 5.1 on 2024-09-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('father_name', models.CharField(max_length=25)),
                ('grand_father_name', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=25)),
                ('nationality', models.CharField(max_length=25)),
                ('general_directorate', models.CharField(max_length=25)),
                ('directorate', models.CharField(max_length=25)),
                ('head', models.CharField(max_length=25)),
                ('job_position', models.CharField(max_length=25)),
                ('remarks', models.CharField(max_length=255)),
                ('staus', models.CharField(max_length=25)),
                ('religion', models.CharField(max_length=25)),
                ('degree', models.CharField(choices=[('H', 'High School'), ('B', 'Bachelor'), ('M', 'Master'), ('P', 'Phd'), ('A', 'Associate Professor')], max_length=1)),
                ('mraital_status', models.CharField(choices=[('S', 'SingleM'), ('M', 'Married'), ('W', 'Widdow')], max_length=1)),
                ('gender', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2)),
            ],
        ),
    ]
