# Generated by Django 5.1 on 2024-09-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_remove_province_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degree',
            old_name='title',
            new_name='name',
        ),
    ]
