# Generated by Django 5.1 on 2024-09-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='degree',
            field=models.CharField(choices=[('H', 'High School'), ('B', 'Bachelor'), ('M', 'Master'), ('P', 'Phd'), ('A', 'Associate Professor')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='directorate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='father_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='general_directorate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='grand_father_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='head',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='place_of_birth',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='religion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='staus',
            field=models.CharField(max_length=50),
        ),
    ]
