# Generated by Django 5.1 on 2024-09-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_rename_course_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
