# Generated by Django 5.1 on 2024-09-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_alter_employee_degree_alter_employee_directorate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('report', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=255)),
            ],
        ),
    ]
