# Generated by Django 5.1 on 2024-09-13 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0003_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HR.major'),
        ),
    ]
