# Generated by Django 5.1 on 2024-09-13 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0005_department_district_grade_jobposition_organization_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationTpye',
            new_name='OrganizationType',
        ),
    ]
