# Generated by Django 5.1 on 2024-09-15 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0006_rename_organizationtpye_organizationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='province',
            field=models.ForeignKey(default='kabul', on_delete=django.db.models.deletion.CASCADE, to='HR.province'),
        ),
        migrations.AddField(
            model_name='province',
            name='country',
            field=models.ForeignKey(default='Kabul', on_delete=django.db.models.deletion.CASCADE, to='HR.country'),
        ),
    ]
