# Generated by Django 5.1 on 2024-09-15 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0007_district_province_province_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='province',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='HR.province'),
        ),
    ]
